// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID          string  `json:"id"`
	CustomerID  string  `json:"customerId"`
	Status      string  `json:"status"`
	TotalAmount float64 `json:"totalAmount"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Query struct {
}
